services:
  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/sit725-group-88?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb_data: